[Eth]
SyncMode = "snap"

[Node]
DataDir = "Bahamut/sahara/datadirs/execution/"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = "127.0.0.1"
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
ListenAddr = ":30303"
